baseurl = "http://zhuyong.me"
disablePathToLower = false
languageCode = "en-us"
title = "Zhu Yong"
theme = "hugo-octopress"

# Number of blog posts displayed in each page
paginate = 10

[permalinks]
post = "/blog/:year/:month/:day/:title/" # change the post URL to look like the old ones

# Make tags and categories work
#[indexes]
#	tag = "tags"
#	category = "categories"

[taxonomies]
	tag = "tags"
	category = "categories"

[params]

	# If false, all of the post will appear on front page (and in pagination)
	truncate = true

	# Author's name (this will appear in metadata and under posts)
	author = "Zhu Yong"

	# This text appears in the site header under website title
	subtitle = "$ echo \"Be Persistent, Be Patient\" >> ~/.life"

	# Used in the search engine
	searchEngineURL = "https://www.google.com/search"

	# Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
	continueReadingText = "Read More"

	# Google analytics code
	googleAnalytics = "UA-46972014-1"

	# Disqus shortcode
	# Disable comments for a specific post by adding "comments: false" in its frontmatter
	disqusShortname = "zhuyong"

	rss = true  # switch to true to enable RSS icon link

	# Set to true to use a text label for RSS instead of an icon
	# This is overwritten by the `rss` setting
	textrss = false

	# Website's default description
	defaultDescription = ""

	# Populate this with your own search keywords - these will appear in the meta tags
	defaultKeywords = ["yongzhy" , "Zhu Yong" , "Embedded Software" , "Firmware"]

	sidebarHeader = "<img src='/favicon_32x32.png' />  Zhu Yong"
	sidebarText = "Embedded System Software Engineer"

	##################### Sidebar Icons ###############################
	github = "https://github.com/yongzhy/"
	bitbucket = "https://bitbucket.org/yongzhy/"
	stackOverflow = "http://stackoverflow.com/users/1002691/yongzhy"
	linkedin = "https://www.linkedin.com/in/yongzhy"

	##################### Sidebar #####################################
	sidebarMenuEnabled = true
	sidebarRecentLimit = 6

	generateTaxonomyList = true
	sortTaxonomyAlphabetical = true

	############# Code Highlight ######################################
	# Keep it as false please, the css file contains the code for highlighting
	pygmentsuseclasses = false

	# If nothing is set, then solarized_light is used
	# Other styles can be viewed in [http://pygments.org/](http://pygments.org/)
	pygmentsstyle = "solarized_dark"

	# Highlight shortcode and code fences (```) will be treated similarly
	pygmentscodefences = true

	# pygments options can be added here
	# Hugo supports these pygments options: style, encoding, noclasses, hl_lines, linenos
	# for example: pygmentsoptions = "linenos=true"
	pygmentsoptions = "linenos=true"


[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -10

[[menu.main]]
  Name = "Archives"
  URL = "/blog/archive/"
  weight = -5

[[menu.main]]
  Name = "Categories"
  URL = "/categories/"
  weight = -5  
